/////////////////////////////////////////////////////////////////////////////
//
//  svc_statistics.c: System Statistics Services
//                                            2014.04.01  Ryu SinWook

///////////////////////////////////////

#include "statistics.h"

///////////////////////////////////////


///////////////////////////////////////
//
//  Function: SVC_SaveStatisticsDataToFile()
//      - Service Name: RMGR_SERV_GETSTATISTIC

int SVC_SaveStatisticsDataToFile(int nRobot, int nVerboseOpt)
{
    static const char szFileComment[] = 
        "# This file is for Statistics Data info\n"
        "#  - Power On, Servo On, Moving, Welding time & distance etc.\n"
        "# Copyright (c) 2014 "
        "Daewoo Shipbuilding and Marine Engineering Co., Ltd.,\n"
        "# * param index is equal to robot index [Unit: [date]yy:mm:dd [time]hh:mm:ss [dist]mm]\n"
        "#   Caution! Do not edit this file manually!!\n"
        "#   Can be modified by RM Service Request, automatically generated\n"
        "\n";
    FILE*   fp;
    char szStatisticsFileName[PATH_NAME_BUFFER_SIZE] = "";
    int  iIdx;

#if defined(_MSC_VER)
    errno_t errno;
#endif

    DANDY_ASSERT(nRobot >= 0 && nRobot < MAX_ROBOT_COUNT);
    
    memcpy(szStatisticsFileName, g_pszWorkDir, strlen(g_pszWorkDir)+1);

    // Absolute path define
    CRT_strcat(szStatisticsFileName,
               PATH_NAME_BUFFER_SIZE,
               DEF_STATISTIC_FILENAME);

#if defined(__QNXNTO__)
    fp = fopen(szStatisticsFileName, "w+t");
#else
    errno = fopen_s(&fp, szStatisticsFileName, "w+t");
#endif
    
    if (fp == NULL)
    {
        VERBOSE_ERROR("Cannot open statistics file for write : '%s'\n",
                      DEF_STATISTIC_FILENAME);
        SVC_DefineErrorState(ON, SVC_ERR_STATISTICS_DATA_SAVING);
        return SVC_ERR_STATISTICS_DATA_SAVING;
    }
    else
    {
        if(nVerboseOpt != OPT_QUITE)
        {
            VERBOSE_MESSAGE("Open Done! statistics data file for write : '%s'\n",
                            szStatisticsFileName);
        }
    }
    
    // write comment
    fputs(szFileComment, fp);

    // section
    fprintf(fp, "[statis%d]\n\n", nRobot + 1);
    fprintf(fp, "#####################################################\n");
    
    ////////////////
    // field
    
    //////////////////////////////////////////////////////////////////////
    // RESET_DATE = yy:mm:dd

    fputs(STAT_KEY_TIME_ROBOT_RESET_DATE " = ", fp);
    fprintf(fp, STAT_FORMAT_DATE "\n",
                g_StatisData.DateReset.nYear,
                g_StatisData.DateReset.nMonth,
                g_StatisData.DateReset.nDay);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // RESET_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_RESET_TIME " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeReset.nHour,
                g_StatisData.TimeReset.nMinute,
                g_StatisData.TimeReset.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // PWRON_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_PWRON " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimePowerOn.nHour,
                g_StatisData.TimePowerOn.nMinute,
                g_StatisData.TimePowerOn.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // SRVON_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_SRVON " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeServoOn.nHour,
                g_StatisData.TimeServoOn.nMinute,
                g_StatisData.TimeServoOn.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // JOBEXE_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_JOBEXE " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeJobExec.nHour,
                g_StatisData.TimeJobExec.nMinute,
                g_StatisData.TimeJobExec.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // ERROR_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_ERROR " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeError.nHour,
                g_StatisData.TimeError.nMinute,
                g_StatisData.TimeError.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // STOP_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_STOP " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeStop.nHour,
                g_StatisData.TimeStop.nMinute,
                g_StatisData.TimeStop.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // MOVE_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_MOVE " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeMove.nHour,
                g_StatisData.TimeMove.nMinute,
                g_StatisData.TimeMove.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // WELD_TIME = hh:mm:ss

    fputs(STAT_KEY_TIME_ROBOT_WELD " = ", fp);
    fprintf(fp, STAT_FORMAT_TIME "\n",
                g_StatisData.TimeWeld.nHour,
                g_StatisData.TimeWeld.nMinute,
                g_StatisData.TimeWeld.nSecond);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // FILLET_WELD_DIST = 0000.00

    fputs(STAT_KEY_DIST_ROBOT_FILLETWELD " = ", fp);
    fprintf(fp, STAT_FORMAT_DIST "\n",
                g_StatisData.dbDistFilletWeld);
    fprintf(fp, "\n");

    //////////////////////////////////////////////////////////////////////
    // WEAVE_WELD_DIST = 0000.00

    fputs(STAT_KEY_DIST_ROBOT_WEAVEWELD " = ", fp);
    fprintf(fp, STAT_FORMAT_DIST "\n",
                g_StatisData.dbDistWeavWeld);
    fprintf(fp, "\n");


    fprintf(fp, "#####################################################\n");
    fprintf(fp, "################### Error History ###################\n");

    //////////////////////////////////////////////////////////////////////
    // ERR_CNT = 0 ~ MAX_ERROR_STACK_SIZE
    // ERR_STACK_TOP = 0 ~ MAX_ERROR_STACK_SIZE
    // ERR_INDEX = 0 ~ MAX_ERROR_STACK_SIZE
    // ERR_TIME = 2014-04-07 19:42:56
    // ERR_CODE = 18874410
    // ERR_DETAIL = JOBASM_ERR_FILE_OPEN

    fputs(STAT_KEY_ERROR_HISTORY_COUNT " = ", fp);
    fprintf(fp, "%d\n",
                g_ErrCodeStack.nErrCnt);
    fprintf(fp, "\n");

    fputs(STAT_KEY_ERROR_HISTORY_ST_TOP " = ", fp);
    fprintf(fp, "%d\n",
                g_ErrCodeStack.nTop);
    fprintf(fp, "\n");

    if(g_ErrCodeStack.szErrStackSysTime != NULL &&
       g_ErrCodeStack.g_szErrContent != NULL )
    {
        for(iIdx = 0; iIdx < g_nErrHistorySaveMaxCnt; iIdx++)
        {
            fputs(STAT_KEY_ERROR_HISTORY_INDEX " = ", fp);
            fprintf(fp, "%d\n",
                        iIdx);

            fputs(STAT_KEY_ERROR_HISTORY_TIME " = ", fp);
            if(sizeof(g_ErrCodeStack.szErrStackSysTime[iIdx]) <= 2)
            {
                fprintf(fp, "%s\n",
                            "0");
            }
            else
            {
                fprintf(fp, "%s\n",
                            g_ErrCodeStack.szErrStackSysTime[iIdx]);
            }

            fputs(STAT_KEY_ERROR_HISTORY_CODE " = ", fp);
            fprintf(fp, "%d, %d\n",
                        g_ErrCodeStack.nErrStack[iIdx],
                        g_ErrCodeStack.fErrorActiveState[iIdx]);

            fputs(STAT_KEY_ERROR_HISTORY_DETAIL " = ", fp);
            if(sizeof(g_ErrCodeStack.g_szErrContent[iIdx]) <= 2)
            {
                fprintf(fp, "%s\n",
                            "null");
            }
            else
            {
                fprintf(fp, "%s\n",
                            g_ErrCodeStack.g_szErrContent[iIdx]);
            }


            fprintf(fp, "\n");
        }
    }

    fclose(fp);

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_DefineStatisticsDataPacket()
//
static int _loc_Fn_DefineStatisticsDataPacket(void)
{
    /* Reply Message */
    // reset date
    RM_reply_packet.Data.statistics.DateReset.nYear  = g_StatisData.DateReset.nYear;
    RM_reply_packet.Data.statistics.DateReset.nMonth = g_StatisData.DateReset.nMonth;
    RM_reply_packet.Data.statistics.DateReset.nDay   = g_StatisData.DateReset.nDay;

    // reset time
    RM_reply_packet.Data.statistics.TimeReset.nHour   = g_StatisData.TimeReset.nHour;
    RM_reply_packet.Data.statistics.TimeReset.nMinute = g_StatisData.TimeReset.nMinute;
    RM_reply_packet.Data.statistics.TimeReset.nSecond = g_StatisData.TimeReset.nSecond;

    // power on time
    RM_reply_packet.Data.statistics.TimePowerOn.nHour   = g_StatisData.TimePowerOn.nHour;
    RM_reply_packet.Data.statistics.TimePowerOn.nMinute = g_StatisData.TimePowerOn.nMinute;
    RM_reply_packet.Data.statistics.TimePowerOn.nSecond = g_StatisData.TimePowerOn.nSecond;
    
    // servo on time
    RM_reply_packet.Data.statistics.TimeServoOn.nHour   = g_StatisData.TimeServoOn.nHour;
    RM_reply_packet.Data.statistics.TimeServoOn.nMinute = g_StatisData.TimeServoOn.nMinute;
    RM_reply_packet.Data.statistics.TimeServoOn.nSecond = g_StatisData.TimeServoOn.nSecond;

    // job exec time
    RM_reply_packet.Data.statistics.TimeJobExec.nHour   = g_StatisData.TimeJobExec.nHour;
    RM_reply_packet.Data.statistics.TimeJobExec.nMinute = g_StatisData.TimeJobExec.nMinute;
    RM_reply_packet.Data.statistics.TimeJobExec.nSecond = g_StatisData.TimeJobExec.nSecond;

    // error time
    RM_reply_packet.Data.statistics.TimeError.nHour   = g_StatisData.TimeError.nHour;
    RM_reply_packet.Data.statistics.TimeError.nMinute = g_StatisData.TimeError.nMinute;
    RM_reply_packet.Data.statistics.TimeError.nSecond = g_StatisData.TimeError.nSecond;

    // stop time
    RM_reply_packet.Data.statistics.TimeStop.nHour   = g_StatisData.TimeStop.nHour;
    RM_reply_packet.Data.statistics.TimeStop.nMinute = g_StatisData.TimeStop.nMinute;
    RM_reply_packet.Data.statistics.TimeStop.nSecond = g_StatisData.TimeStop.nSecond;

    // move time
    RM_reply_packet.Data.statistics.TimeMove.nHour   = g_StatisData.TimeMove.nHour;
    RM_reply_packet.Data.statistics.TimeMove.nMinute = g_StatisData.TimeMove.nMinute;
    RM_reply_packet.Data.statistics.TimeMove.nSecond = g_StatisData.TimeMove.nSecond;

    // weld time
    RM_reply_packet.Data.statistics.TimeWeld.nHour   = g_StatisData.TimeWeld.nHour;
    RM_reply_packet.Data.statistics.TimeWeld.nMinute = g_StatisData.TimeWeld.nMinute;
    RM_reply_packet.Data.statistics.TimeWeld.nSecond = g_StatisData.TimeWeld.nSecond;

    // fillet joint weld distance
    RM_reply_packet.Data.statistics.dbDistFilletWeld = g_StatisData.dbDistFilletWeld;

    // weave weld distance
    RM_reply_packet.Data.statistics.dbDistWeavWeld   = g_StatisData.dbDistWeavWeld;

    RM_reply_packet.nCode      = RM_packet.nCode;
    RM_reply_packet.nValue     = RM_packet.nValue;
    RM_reply_packet.nDataSize  = sizeof(RMGR_STATISTICS_DATA);

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_WriteStatisticsTime()
//
static int _loc_Fn_WriteStatisticsTime(void)
{
    // power on time
    g_StatisData.TimePowerOn.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_POWERON] / 3600;
    g_StatisData.TimePowerOn.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_POWERON] % 3600) / 60;
    g_StatisData.TimePowerOn.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_POWERON] % 60;

    // servo on time
    g_StatisData.TimeServoOn.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_SERVOON] / 3600;
    g_StatisData.TimeServoOn.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_SERVOON] % 3600) / 60;
    g_StatisData.TimeServoOn.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_SERVOON] % 60;

    // job exec time
    g_StatisData.TimeJobExec.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_JOBEXEC] / 3600;
    g_StatisData.TimeJobExec.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_JOBEXEC] % 3600) / 60;
    g_StatisData.TimeJobExec.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_JOBEXEC] % 60;

    // error time
    g_StatisData.TimeError.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_ERROR] / 3600;
    g_StatisData.TimeError.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_ERROR] % 3600) / 60;
    g_StatisData.TimeError.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_ERROR] % 60;

    // stop time
    g_StatisData.TimeStop.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_STOP] / 3600;
    g_StatisData.TimeStop.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_STOP] % 3600) / 60;
    g_StatisData.TimeStop.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_STOP] % 60;

    // move time
    g_StatisData.TimeMove.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_MOVE] / 3600;
    g_StatisData.TimeMove.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_MOVE] % 3600) / 60;
    g_StatisData.TimeMove.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_MOVE] % 60;

    // weld time
    g_StatisData.TimeWeld.nHour   =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_WELD] / 3600;
    g_StatisData.TimeWeld.nMinute = (g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_WELD] % 3600) / 60;
    g_StatisData.TimeWeld.nSecond =  g_dwRobotStatTime.rgdwTime[ROBOT_STAT_TIME_WELD] % 60;

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_WriteStatisticsDist()
//
static int _loc_Fn_WriteStatisticsDist(void)
{
    // fillet joint weld distance
    g_StatisData.dbDistFilletWeld = g_dbRobotStatDist.dbDistFilletWeld;
    
    // weave weld distance
    g_StatisData.dbDistWeavWeld = g_dbRobotStatDist.dbDistWeavWeld;

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_ShowStatisticsData()
//
static void _loc_Fn_ShowStatisticsData(void)
{
    VERBOSE_VERBOSE("\v\n<- System Statistics Data Info ->\n");

    VERBOSE_VERBOSE("\vPower ON Time: "STAT_FORMAT_TIME"\t",
                    g_StatisData.TimePowerOn.nHour,
                    g_StatisData.TimePowerOn.nMinute,
                    g_StatisData.TimePowerOn.nSecond);
    VERBOSE_VERBOSE("\vServo ON Time: "STAT_FORMAT_TIME"\n",
                    g_StatisData.TimeServoOn.nHour,
                    g_StatisData.TimeServoOn.nMinute,
                    g_StatisData.TimeServoOn.nSecond);
    VERBOSE_VERBOSE("\vJob Exec Time: "STAT_FORMAT_TIME"\t",
                    g_StatisData.TimeJobExec.nHour,
                    g_StatisData.TimeJobExec.nMinute,
                    g_StatisData.TimeJobExec.nSecond);
    VERBOSE_VERBOSE("\vError Time: "STAT_FORMAT_TIME"\n",
                    g_StatisData.TimeError.nHour,
                    g_StatisData.TimeError.nMinute,
                    g_StatisData.TimeError.nSecond);
    VERBOSE_VERBOSE("\vMove Time: "STAT_FORMAT_TIME"\t",
                    g_StatisData.TimeMove.nHour,
                    g_StatisData.TimeMove.nMinute,
                    g_StatisData.TimeMove.nSecond);
    VERBOSE_VERBOSE("\vWeld Time: "STAT_FORMAT_TIME"\n",
                    g_StatisData.TimeWeld.nHour,
                    g_StatisData.TimeWeld.nMinute,
                    g_StatisData.TimeWeld.nSecond);

    VERBOSE_VERBOSE("\vFillet Weld Distance: "STAT_FORMAT_DIST" mm\t",
                    g_StatisData.dbDistFilletWeld);

    VERBOSE_VERBOSE("\vWeave Weld Distance: "STAT_FORMAT_DIST" mm\n",
                    g_StatisData.dbDistWeavWeld);
    
    VERBOSE_VERBOSE("\v\n");
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: Fn_WriteStatisticsData()
//
int Fn_WriteStatisticsData(int nVerboseOpt)
{
    _loc_Fn_WriteStatisticsTime();

    _loc_Fn_WriteStatisticsDist();

    if(nVerboseOpt != OPT_QUITE)
    {
        _loc_Fn_ShowStatisticsData();
    }

    _loc_Fn_DefineStatisticsDataPacket();

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_ResetStatisticsTime()
//
int _loc_Fn_ResetStatisticsTime(void)
{
    int iMember;

    for(iMember = 0; iMember < ROBOT_STAT_TIME_COUNT; iMember++)
    {
        g_dwRobotStatTime.rgdwTime[iMember] = 0;
    }

    return RESULT_OK;
}


/////////////////////////////////////////////////////////////////////////////
//
//  Function: _loc_Fn_ResetStatisticsDist()
//
int _loc_Fn_ResetStatisticsDist(void)
{
    int iMember;

    for(iMember = 0; iMember < ROBOT_STAT_DIST_COUNT; iMember++)
    {
        g_dbRobotStatDist.rgdbDistance[iMember] = 0;
    }

    return RESULT_OK;
}



/////////////////////////////////////////////////////////////////////////////
//
//  Function: Fn_ResetStatisticsData()
//
int Fn_ResetStatisticsData(void)
{
    Fn_GetSystemTime();

    g_StatisData.DateReset.nYear    = curr_time.nYear;
    g_StatisData.DateReset.nMonth   = curr_time.nMonth;
    g_StatisData.DateReset.nDay     = curr_time.nDay;
    
    g_StatisData.TimeReset.nHour    = curr_time.nHour;
    g_StatisData.TimeReset.nMinute  = curr_time.nMinute;
    g_StatisData.TimeReset.nSecond  = curr_time.nSec;

    _loc_Fn_ResetStatisticsTime();
    _loc_Fn_WriteStatisticsTime();

    _loc_Fn_ResetStatisticsDist();
    _loc_Fn_WriteStatisticsDist();

    _loc_Fn_ShowStatisticsData();

    _loc_Fn_DefineStatisticsDataPacket();

    return RESULT_OK;
}

///////////////////////////////////////
//
//  Function: SVC_GetStatisticsData()
//      - Service Name: RMGR_SERV_GETSTATISTIC

int SVC_GetStatisticsData(int nOpt)
{
    int nRet = 0;

    switch (nOpt)
    {
    case RCON_STATISTICS_GET:
        Fn_WriteStatisticsData(OPT_NULL);
        nRet = SVC_SaveStatisticsDataToFile(ROBOT_0_INDEX, OPT_NULL);
        VERBOSE_MESSAGE("Statistics Data Write Done!\n");
        break;

    case RCON_STATISTICS_RESET_ALL:
        Fn_ResetStatisticsData();
        nRet = SVC_SaveStatisticsDataToFile(ROBOT_0_INDEX, OPT_NULL);
        VERBOSE_MESSAGE("Statistics Data Reset Done!\n");
        break;
    }

    if(nRet != RESULT_OK)
    {
        return RESULT_ERROR;
    }

    return RESULT_OK;
}
